#!/stage1/busybox sh
export _PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

while ! busybox test -d /sys/dev/block/179:0 ; do
	busybox echo "waiting for internal mmc" >>boot.txt
	busybox sleep 1
done

busybox mount -t yaffs2 -o ro /dev/block/mtdblock1 /ramdisk
busybox mount -t yaffs2 -o ro /dev/block/mtdblock2 /ramdisk-recovery

	busybox echo 'RECOVERY BOOT' >>boot.txt
	busybox rm -fr /cache/.startrecovery
	image=/ramdisk-recovery/ramdisk-recovery.img
	busybox echo "loading ramdisk-recovery.img" >>boot.txt

	# disable lpm
	busybox echo 0 > /sys/class/power_supply/battery/charging_mode_booting

busybox gzip -d < $image > /stage1/ramdisk.cpio

busybox umount /ramdisk
busybox umount /ramdisk-recovery

busybox cpio -ui < /stage1/ramdisk.cpio

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -rf /stage1 /ramdisk* /dev/*
export PATH="${_PATH}"
exec /init
