obj-y	+= mach-aries.o aries-rfkill.o bigmem.o
obj-y	+= aries-vibrator.o
obj-y	+= aries-btlpm.o
obj-y	+= aries-watchdog.o
obj-y	+= aries-panel.o

obj-$(CONFIG_PHONE_ARIES)	+= dev-s1-phone.o
obj-$(CONFIG_PHONE_ARIES)	+= level.o
obj-$(CONFIG_PHONE_ARIES_STE)	+= dev-s1-phone.o
obj-$(CONFIG_PHONE_ARIES_STE)	+= level.o
obj-$(CONFIG_PHONE_ARIES_CDMA)	+= dev-s1-phone.o
obj-$(CONFIG_PHONE_ARIES_CDMA)	+= level.o
obj-$(CONFIG_PHONE_CRESPO)	+= dev-aries-phone.o